<a href="https://colab.research.google.com/github/oshikatiwari/Semantic-Book-Recommender/blob/main/sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

books = pd.read_csv(
    "/content/drive/MyDrive/book recommender/data/books_with_categories.csv"
)

Mounted at /content/drive

In [ ]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=None,
    device=0
)

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  329MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  329MB

model.safetensors: downloading bytes:           |  0.00B

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [ ]:
classifier("I love this!")

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.00852868054062128},
  {'label': 'neutral', 'score': 0.005764591973274946},
  {'label': 'anger', 'score': 0.004419785924255848},
  {'label': 'sadness', 'score': 0.0020923891570419073},
  {'label': 'disgust', 'score': 0.001611991785466671},
  {'label': 'fear', 'score': 0.00041385178337804973}]]

In [ ]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [ ]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548413634300232},
  {'label': 'neutral', 'score': 0.16985207796096802},
  {'label': 'sadness', 'score': 0.11640888452529907},
  {'label': 'surprise', 'score': 0.02070062793791294},
  {'label': 'disgust', 'score': 0.019100705161690712},
  {'label': 'joy', 'score': 0.015161297284066677},
  {'label': 'anger', 'score': 0.003935146611183882}]]

In [ ]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296026945114136},
  {'label': 'neutral', 'score': 0.1403856873512268},
  {'label': 'fear', 'score': 0.06816219538450241},
  {'label': 'joy', 'score': 0.04794241115450859},
  {'label': 'anger', 'score': 0.009156348183751106},
  {'label': 'disgust', 'score': 0.00262847519479692},
  {'label': 'sadness', 'score': 0.0021221605129539967}],
 [{'label': 'neutral', 'score': 0.44937071204185486},
  {'label': 'disgust', 'score': 0.2735914885997772},
  {'label': 'joy', 'score': 0.10908304899930954},
  {'label': 'sadness', 'score': 0.09362724423408508},
  {'label': 'anger', 'score': 0.040478333830833435},
  {'label': 'surprise', 'score': 0.02697017975151539},
  {'label': 'fear', 'score': 0.006879060063511133}],
 [{'label': 'neutral', 'score': 0.6462162137031555},
  {'label': 'sadness', 'score': 0.2427332103252411},
  {'label': 'disgust', 'score': 0.04342261329293251},
  {'label': 'surprise', 'score': 0.028300540521740913},
  {'label': 'joy', 'score': 0.014211442321538925},
  {'label': 'fear', 'score': 0.014084079302847385},
  {'label': 'anger', 'score': 0.01103188470005989}],
 [{'label': 'fear', 'score': 0.928167998790741},
  {'label': 'anger', 'score': 0.03219102695584297},
  {'label': 'neutral', 'score': 0.012808729894459248},
  {'label': 'sadness', 'score': 0.008756889030337334},
  {'label': 'surprise', 'score': 0.008597911335527897},
  {'label': 'disgust', 'score': 0.008431846275925636},
  {'label': 'joy', 'score': 0.001045582932420075}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104170888662338},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393994972109795},
  {'label': 'surprise', 'score': 0.0022869433742016554},
  {'label': 'anger', 'score': 0.0018428893527016044},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327971935272217},
  {'label': 'disgust', 'score': 0.03771771863102913},
  {'label': 'neutral', 'score': 0.01589190773665905},
  {'label': 'sadness', 'score': 0.006444551516324282},
  {'label': 'anger', 'score': 0.005025018472224474},
  {'label': 'surprise', 'score': 0.0015812073834240437},
  {'label': 'fear', 'score': 0.0005423100665211678}],
 [{'label': 'joy', 'score': 0.6528703570365906},
  {'label': 'neutral', 'score': 0.25427502393722534},
  {'label': 'surprise', 'score': 0.0680830255150795},
  {'label': 'sadness', 'score': 0.009908979758620262},
  {'label': 'disgust', 'score': 0.006512209307402372},
  {'label': 'anger', 'score': 0.00482131028547883},
  {'label': 'fear', 'score': 0.0035290152300149202}],
 [{'label': 'neutral', 'score': 0.5494765639305115},
  {'label': 'sadness', 'score': 0.1116902083158493},
  {'label': 'disgust', 'score': 0.10400670021772385},
  {'label': 'surprise', 'score': 0.07876556366682053},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136282742023468},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [ ]:
sentences=books["description"][0].split(".")
predictions=classifier(sentences)

In [ ]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [ ]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296026945114136},
 {'label': 'neutral', 'score': 0.1403856873512268},
 {'label': 'fear', 'score': 0.06816219538450241},
 {'label': 'joy', 'score': 0.04794241115450859},
 {'label': 'anger', 'score': 0.009156348183751106},
 {'label': 'disgust', 'score': 0.00262847519479692},
 {'label': 'sadness', 'score': 0.0021221605129539967}]

In [ ]:
sorted(predictions[0],key=lambda x:x["label"])

[{'label': 'anger', 'score': 0.009156348183751106},
 {'label': 'disgust', 'score': 0.00262847519479692},
 {'label': 'fear', 'score': 0.06816219538450241},
 {'label': 'joy', 'score': 0.04794241115450859},
 {'label': 'neutral', 'score': 0.1403856873512268},
 {'label': 'sadness', 'score': 0.0021221605129539967},
 {'label': 'surprise', 'score': 0.7296026945114136}]

In [ ]:
import numpy as np

emotion_labels = [
    "anger",
    "disgust",
    "fear",
    "joy",
    "sadness",
    "surprise",
    "neutral"
]

isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}

    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])

        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(
                sorted_predictions[index]["score"]
            )

    return {
        label: np.max(scores)
        for label, scores in per_emotion_scores.items()
    }

In [ ]:
for i in range(10):
    isbn.append(books["isbn13"][i])

    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)

    max_scores = calculate_max_emotion_scores(predictions)

    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [ ]:
emotion_scores

{'anger': [np.float64(0.0641336739063263),
  np.float64(0.6126185059547424),
  np.float64(0.6126185059547424),
  np.float64(0.0641336739063263),
  np.float64(0.35148391127586365),
  np.float64(0.35148391127586365),
  np.float64(0.08141247183084488),
  np.float64(0.08141247183084488),
  np.float64(0.2322249710559845),
  np.float64(0.2322249710559845)],
 'disgust': [np.float64(0.2735914885997772),
  np.float64(0.3482844829559326),
  np.float64(0.3482844829559326),
  np.float64(0.10400670021772385),
  np.float64(0.15072263777256012),
  np.float64(0.15072263777256012),
  np.float64(0.1844954937696457),
  np.float64(0.1844954937696457),
  np.float64(0.727174699306488),
  np.float64(0.727174699306488)],
 'fear': [np.float64(0.928167998790741),
  np.float64(0.9425278306007385),
  np.float64(0.9425278306007385),
  np.float64(0.9723208546638489),
  np.float64(0.36070623993873596),
  np.float64(0.36070623993873596),
  np.float64(0.09504325687885284),
  np.float64(0.09504325687885284),
  np.float64(0.05136282742023468),
  np.float64(0.05136282742023468)],
 'joy': [np.float64(0.9327971935272217),
  np.float64(0.7044215202331543),
  np.float64(0.7044215202331543),
  np.float64(0.7672368884086609),
  np.float64(0.25188079476356506),
  np.float64(0.25188079476356506),
  np.float64(0.040564440190792084),
  np.float64(0.040564440190792084),
  np.float64(0.04337584972381592),
  np.float64(0.04337584972381592)],
 'sadness': [np.float64(0.6462162137031555),
  np.float64(0.887939453125),
  np.float64(0.887939453125),
  np.float64(0.5494765639305115),
  np.float64(0.732685387134552),
  np.float64(0.732685387134552),
  np.float64(0.8843895196914673),
  np.float64(0.8843895196914673),
  np.float64(0.6213927268981934),
  np.float64(0.6213927268981934)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493),
  np.float64(0.4758807122707367),
  np.float64(0.4758807122707367),
  np.float64(0.1116902083158493),
  np.float64(0.1116902083158493)],
 'neutral': [np.float64(0.7296026945114136),
  np.float64(0.2525450885295868),
  np.float64(0.2525450885295868),
  np.float64(0.07876556366682053),
  np.float64(0.07876556366682053),
  np.float64(0.07876556366682053),
  np.float64(0.07876556366682053),
  np.float64(0.07876556366682053),
  np.float64(0.27190276980400085),
  np.float64(0.27190276980400085)]}

In [ ]:
len(books)

6651

In [ ]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]

isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])

    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)

    max_scores = calculate_max_emotion_scores(predictions)

    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 6651/6651 [03:22<00:00, 32.90it/s]

In [ ]:
emotions_df=pd.DataFrame(emotion_scores)
emotions_df["isbn13"]=isbn

In [ ]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932797,0.646216,0.967158,0.729603,9780002005883
1,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545,9780002261982
2,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545,9780002261982
3,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766,9780006178736
4,0.351484,0.150723,0.360706,0.251881,0.732685,0.111690,0.078766,9780006280897
...,...,...,...,...,...,...,...,...
6646,0.064134,0.114383,0.051363,0.400263,0.883199,0.111690,0.227765,9788173031014
6647,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
6648,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
6649,0.064134,0.104007,0.459269,0.759455,0.951104,0.368111,0.078766,9788185300535
6650,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059

In [ ]:
books=pd.merge(books,emotions_df,on="isbn13")

In [ ]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,sadness_x,surprise_x,neutral_x,anger_y,disgust_y,fear_y,joy_y,sadness_y,surprise_y,neutral_y
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,0.646216,0.967158,0.729603,0.064134,0.273591,0.928168,0.932797,0.646216,0.967158,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.887939,0.111690,0.252545,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545
2,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.887939,0.111690,0.252545,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545
3,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.887939,0.111690,0.252545,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545
4,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.887939,0.111690,0.252545,0.612619,0.348284,0.942528,0.704422,0.887939,0.111690,0.252545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15370,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.375755,0.066685,0.057625,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
15371,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.375755,0.066685,0.057625,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
15372,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.375755,0.066685,0.057625,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
15373,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,0.951104,0.368111,0.078766,0.064134,0.104007,0.459269,0.759455,0.951104,0.368111,0.078766
15374,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,0.915193,0.111690,0.078766,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766

In [ ]:
books.to_csv(
    "/content/drive/MyDrive/book recommender/data/books_with_emotions.csv",
    index=False
)

In [ ]:
import os

os.listdir("/content/drive/MyDrive/book recommender/data")

['books_with_categories.csv', 'books_with_emotions.csv']